### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by flypigJ** [BetterNCM/SimpleAudioVisualizer#1]
https://user-images.githubusercontent.com/68471692/212789702-4e38b057-65c7-488f-90af-ea57ca89ff49.mp4

如视频所示，安装后无变化（歌词和评论区卡顿是电脑配置问题
目前有两种猜测
1.与播放页美化插件冲突。我目前使用了2个，分别是refined nowplaying和material you勾选了在播放页启用。
2.神奇的系统原因？？？Windows Dev 25276.1000

**Comment by MinamiHashiRun0** [comment]
+rep
Windows10 21H2 （19044.2486）
重装了BNCM，插件只有可视化音频

**Comment by MinamiHashiRun0** [comment]
> +rep Windows10 21H2 （19044.2486） 重装了BNCM，插件只有可视化音频

更正   重新安装网易云和插件（并且删除C盘betterncm文件夹）可能会有效果，需要打开“LibFrontendPlay”的“启用”选项

**Comment by std-microblock** [comment]
SimpleAudioVisualizer 基于 LibFrontendPlay，必须启用 LibFrontendPlay 才能使用……为什么你要把它禁掉

**Comment by flypigJ** [comment]
> SimpleAudioVisualizer 基于 LibFrontendPlay，必须启用 LibFrontendPlay 才能使用……为什么你要把它禁掉

可是，我开启LibFrontendPlay之后的效果是这样的...
![image](https://user-images.githubusercontent.com/68471692/214515268-d329531b-0053-4c87-af24-9c904e027125.png)
播放按钮直接变灰，进度条不动，playprogress也卡在0，当然也没有声音了。所以说，我是不是应该去LibFrontendPlay下面开issue...?

**Comment by std-microblock** [comment]
> > SimpleAudioVisualizer 基于 LibFrontendPlay，必须启用 LibFrontendPlay 才能使用……为什么你要把它禁掉
> 
> 可是，我开启LibFrontendPlay之后的效果是这样的... ![image](https://user-images.githubusercontent.com/68471692/214515268-d329531b-0053-4c87-af24-9c904e027125.png) 播放按钮直接变灰，进度条不动，playprogress也卡在0，当然也没有声音了。所以说，我是不是应该去LibFrontendPlay下面开issue...?

BetterNCM/LibFrontendPlay#2
