### ISSUE TITLE
调整进度条卡住不动

### ISSUE THREAD

**Issue by Ailrid** [BetterNCM/SimpleAudioVisualizer#2]
![ZY0O2IFK~1DX~Y@7XN8({ K](https://user-images.githubusercontent.com/116699459/214310002-4c767132-3b87-4212-8bd9-c7e38d196d6d.png)
我装了这些之后，再装这个插件，只要我一拖动下面歌曲的进度条，这个进度条就卡住在那里不会动了，但是歌还是会继续播放

**Comment by std-microblock** [comment]
fixed
